# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [169]:
# Assignment 1: Array Creation and Manipulation

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
# Replace all the elements in the third column with 1.
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
import numpy as np

matrix = np.random.randint(1,10,size=(5,5))
matrix[:,2] = 1
print(array)


matrix1 = np.arange(1,17).reshape(4,4)
print(matrix1)
np.fill_diagonal(matrix1,0)
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10  6]
 [ 8  9  5]
 [ 9 10  9]]


In [171]:
# Assignment 2: Array Indexing and Slicing

#  1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
matrix = np.arange(1,37).reshape(6,6)
print(matrix)

sub_matrix = array[2:5,1:4]
print(sub_matrix)

#  2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
# array1 = np.random.rand(5,5)
matrix1 = np.random.randint(1,20,size=(5,5))
print(matrix1)
# border_elements = array1[0,:]
# border_elements = array1[4,:]
# border_elements = array1[1:-1,0]
# border_elements = array1[1:-1,-1]
border_elements = np.concatenate((matrix1[0,:],matrix1[4,:],matrix1[1:-1,0],matrix1[1:-1,-1]))
print(border_elements)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[8 9]]
[[ 6 16 11  2 19]
 [13 19 11  7  5]
 [19 16  3  3 19]
 [ 9  7 10 14  6]
 [16 17  2  5 12]]
[ 6 16 11  2 19 16 17  2  5 12 13 19  9  5 19  6]


In [173]:
# Assignment 3: Array Operations

#     Create two NumPy arrays of shape (3, 4) filled with random integers. 
#     Perform element-wise addition, subtraction, multiplication, and division.
matrix1 = np.random.randint(1,10,size=(3,4))
matrix2 = np.random.randint(1,10,size=(3,4))
print("Original Arrays")
print(matrix1)
print(matrix2)

addition_array = np.add(matrix1,matrix2)
subtraction_array = np.subtract(matrix1,matrix2)
multiplication_array = np.multiply(matrix1,matrix2)
division_array = np.divide(matrix1,matrix2)
print("Arrays Operation")
print("\n Addition")
print(addition_array)
print("\n Subtraction")
print(subtraction_array)
print("\n Multiplication")
print(multiplication_array)
print("\n Division \n")
print(division_array)

#     Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
matrix = np.arange(1,17).reshape(4,4)
print("\n Array")
print(array)
row_sum = np.sum(matrix,axis =1)
col_sum = np.sum(matrix,axis=0)
print("\n Array Sum:")
print(row_sum)
print(col_sum)

Original Arrays
[[5 8 7 5]
 [6 4 9 4]
 [2 1 8 1]]
[[3 2 1 1]
 [8 5 7 7]
 [4 8 2 2]]
Arrays Operation

 Addition
[[ 8 10  8  6]
 [14  9 16 11]
 [ 6  9 10  3]]

 Subtraction
[[ 2  6  6  4]
 [-2 -1  2 -3]
 [-2 -7  6 -1]]

 Multiplication
[[15 16  7  5]
 [48 20 63 28]
 [ 8  8 16  2]]

 Division 

[[1.66666667 4.         7.         5.        ]
 [0.75       0.8        1.28571429 0.57142857]
 [0.5        0.125      4.         0.5       ]]

 Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Array Sum:
[10 26 42 58]
[28 32 36 40]


In [179]:
# Assignment 4: Statistical Operations

#     Create a NumPy array of shape (5, 5) filled with random integers.
#     Compute the mean, median, standard deviation, and variance of the array.
array1 = np.random.randint(1,25,size=(5,5))
print(array1)

mean = np.mean(array1)
median = np.median(array1)
std_deviation = np.std(array1)
var = np.var(array1)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_deviation}")
print(f"variance: {var}")

#     Create a NumPy array of shape (3, 3) with values from 1 to 9. 
#     Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
array = np.arange(1,10).reshape(3,3)
# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

[[11  5 22  4 23]
 [ 4 22 23 12 10]
 [ 3  9 24  7 12]
 [13 23 12 21  9]
 [23 22 11  4  3]]
Mean: 13.28
Median: 12.0
Standard Deviation: 7.539336840863393
variance: 56.8416
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [180]:
# Assignment 5: Broadcasting

#     Create a NumPy array of shape (3, 3) filled with random integers. 
#     Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
array1 = np.random.randint(1,11,size=(3,3))
print(array1)
row_array = np.random.randint(1, 11, size=(3,))
print(row_array)
result = array + row_array
print("Resulting array:")
print(result)

#     Create a NumPy array of shape (4, 4) filled with random integers. 
#     Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


[[2 9 9]
 [1 5 5]
 [5 5 7]]
[ 7 10  3]
Resulting array:
[[ 8 12  6]
 [11 15  9]
 [14 18 12]]


In [212]:
# Assignment 6: Linear Algebra

#     Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

determinant = np.linalg.det(matrix)
print(f"Determinant: {determinant}")

inverse = np.linalg.inv(matrix)
print(f"Inverse: {determinant}")

eig_vec = np.linalg.eig(matrix)
print(f"Eigen Vector: {eig_vec}")
#     Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
matrix_1 = np.random.randint(1,5,size=(2,3))
matrxi_2= np.random.randint(1,5,size=(3,2))

print("Matrices")
print(matrix_1)
print(matrxi_2)
print("Matrices Multiplication")
matrix_mul = np.dot(matrix_1,matrxi_2)
print(matrix_mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant: -9.51619735392994e-16
Inverse: -9.51619735392994e-16
Eigen Vector: EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
Matrices
[[1 2 4]
 [1 1 3]]
[[3 1]
 [1 4]
 [4 3]]
Matrices Multiplication
[[21 21]
 [16 14]]


In [224]:
# Assignment 7: Advanced Array Manipulation

#     Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
array_num = np.arange(1,10).reshape(3,3)
reshape_num  = array_num.reshape(1,9)
reshape_num_2 = array_num.reshape(9,1)
print(array_num)
print(reshape_num)
print(reshape_num_2)

#     Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
matrix = np.random.randint(1,10,size=(5,5))
print(matrix)
matrix_flatten = matrix.flatten()
print(matrix_flatten)

matrix_reshape = matrix.reshape(5,5)
print(matrix_reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[8 1 9 5 7]
 [5 3 2 4 6]
 [9 7 8 7 2]
 [9 4 3 3 7]
 [5 7 7 4 9]]
[8 1 9 5 7 5 3 2 4 6 9 7 8 7 2 9 4 3 3 7 5 7 7 4 9]
[[8 1 9 5 7]
 [5 3 2 4 6]
 [9 7 8 7 2]
 [9 4 3 3 7]
 [5 7 7 4 9]]


In [300]:
# Assignment 8: Fancy Indexing and Boolean Indexing

#     Create a NumPy array of shape (5, 5) filled with random integers.
#     Use fancy indexing to extract the elements at the corners of the array.
array = np.random.randint(1,10,size=(5,5))
print(array)

corner_elements1 = array[0:1,0:1]
corner_elements2 = array[-1:,0:1]
corner_elements3 = array[0:1,-1:]
corner_elements4 = array[-1:,-1:]
corner_elements = np.concatenate((array[0:1,0:1],array[-1:,0:1],array[0:1,-1:],array[-1:,-1:]))
# print(corner_elements1)
# print(corner_elements2)
# print(corner_elements3)
# print(corner_elements4)
print(corner_elements)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)



#     Create a NumPy array of shape (4, 4) filled with random integers.
#     Use boolean indexing to set all elements greater than 10 to 10.
array = np.random.randint(1,20,size=(4,4))
print(array)
array[array>10] = 10
print(array)

[[6 1 1 3 3]
 [1 4 1 1 5]
 [5 6 5 4 5]
 [1 1 8 2 6]
 [4 1 8 4 2]]
[[6]
 [4]
 [3]
 [2]]
Corner elements:
[6 3 4 2]
[[18  1 11  6]
 [ 4 12 16 18]
 [ 6 12  2 14]
 [14  1  4  7]]
[[10  1 10  6]
 [ 4 10 10 10]
 [ 6 10  2 10]
 [10  1  4  7]]
